### ISSUE TITLE
https://dream.uboachan.net serves content from https://admin.seisat.su

### ISSUE THREAD

**Issue by pmer** [seisatsu/Dennis#47]
# Issue

Visiting https://dream.uboachan.net/ results in a certificate security error. If the error is bypassed, the content from https://admin.seisat.su/ is served.

# Expected result

Visiting https://dream.uboachan.net/ does not display an error and the content from http://dream.uboachan.net/ is displayed.

**Comment by seisatsu** [comment]
Dennis does not work over a secure connection currently. I should have https automatically redirect to http.

**Comment by seisatsu** [comment]
Fixed by redirecting HTTPS to HTTP.
