### ISSUE TITLE
Port to TinyDB

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Dennis#48]
Port to BlitzDB so we have the option of saving worlds to flat file or MongoDB.

**Comment by seisatsu** [comment]
Change of plan: Abandon MongoDB entirely in favor of BlitzDB. This is more portable, and MongoDB is a pain in the ass to get working on Debian, as well as to upgrade. The authentication mechanism also shifts around frequently, making different versions incompatible with each other. BlitzDB should be one-and-done. There will also need to be a migration tool.

**Comment by pmer** [comment]
Makes sense as MongoDB was designed for a very different type of application anyway. Also, just playing devil's advocate, but what about SQLite?

**Comment by seisatsu** [comment]
If we use plain SQLite, we have to write queries for everything. I did that with the original Dennis and it was extremely unwieldy and didn't feel natural to write. BlitzDB allows just dumping Python data structures into the database which is very transparent and simple to work with. It's kind of like pickling but without the cross-compatibility issues.

If you can find an abstraction layer that lets us just drop Python data structures directly into SQLite, I'm open to suggestions.

**Comment by pmer** [comment]
If it’s already been looked at, then I don’t have any further arguments for it. :)

**Comment by seisatsu** [comment]
I'm setting up to use a similar Python database solution called TinyDB because it's a more mature project. This is started with bd2440dcc3c2c4e6ef17d66d154ec483eae899c6 which will allow me to convert the database of the testing world.
