### ISSUE TITLE
Completion for commands that work on names

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Dennis#49]
Allow completion for non-ambiguous partial names in commands.

Example: If there is an exit called "Big Wooden Door", then `go big` should select for that exit. However, if there is also an exit in the same context (same room in this case) named "Big Plastic Door", then `go big` should reject the command string as ambiguous.

This should also work on commands like `use`, `look`, and `get`, to name a few.

**Comment by jmdejong** [comment]
Preferably it should also work to type `go door` when there is only one door, or `go wooden door` when there are both a "Big Wooden Door" and a "Big Plastic Door"
