### ISSUE TITLE
Sit and lay command

### ISSUE THREAD

**Issue by stadham** [seisatsu/Dennis#64]
Hi,

Can you put in a sit and lay command for chairs and beds?

Thanks

**Comment by seisatsu** [comment]
Currently you can use the action command to do something like "action sat on the chair", and that will show "yourname sat on the chair". Would the sit and lay commands basically be a shortcut for doing this, or would they have some additional effects, like adding an extra line of text such as "yourname is sitting down" when another player looks at you? Please describe how the commands would be invoked and what effects they would have.

Note that the `imbue item` command currently in planning will allow you to assign a custom command to any item, that will make the player broadcast a custom action when that command is used on that item. So, once that's implemented, you will be able to make a chair item that allows a player to "sit on" it, and then says "player sat on the chair" when they do so. So, this may actually be what you are looking for. See #58.

**Comment by stadham** [comment]
I was looking for a command like "sit brown chair" Or "sit on brown chair" then if you look at the player it might say "player sits on brown chair" or something like that.

**Comment by seisatsu** [comment]
These will be implemented, see #65.
