### ISSUE TITLE
Sit, Lay, and Stand Commands

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Dennis#65]
Replaces #64.

The `sit`, `lay`, and `stand` commands affect the player's description and perform a pre-defined action. The `sit` and `lay` commands can be performed by themselves or with an item, and the `stand` command can only be performed on its own, and undoes the description modification from `sit` or `lay`. Trying to `sit` or `lay` while already doing it will `stand`. However, you can move from sitting to laying, and vice versa. The commands detect if the player is already sitting or laying from the presence of certain phrases in the player's description, and detect if they are standing from the absence of those phrases. If the player takes an exit while sitting or laying, they will stand first, but if they leave by teleporting they will not change positions. A player cannot `sit` or `lay` on an item in their inventory, only one that is in the current room.

`sit [item]`
* Without an argument, does the action "player sat down", and adds the line "They are sitting down." to the end of the player's description.
* With an argument, does the action "player sat down on (item)", and adds the line "They are sitting down on (item)." to the end of the player's description.
* Has the aliases `sit on`, `sit down`, and `sit down on`.
* If the name of the item given doesn't start with one of "the", "a", or "an" followed by a space, the word "the" will be added before the name of the item.

`lay [item]`
* Without an argument, does the action "player laid down", and adds the line "They are laying down." to the end of the player's description.
* With an argument, does the action "player laid down on (item)", and adds the line "They are sitting down on (item)." to the end of the player's description.
* Has the aliases `lay on`, `lay down`, and `lay down on`.
* If the name of the item given doesn't start with one of "the", "a", or "an" followed by a space, the word "the" will be added before the name of the item.

`stand`
* Does the action "player stood up", and removes any line starting with "They are sitting down" or "They are laying down" from the player's description.
* Has the alias `stand up`.

**Comment by stadham** [comment]
Thanks looks great. Well done!
